import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface AssetMetric {
  name: string;
  symbol: string;
  finalValue: number;
  profit: number;
  returnPct: number;
  volatility: number;
  category: string;
}

interface ExportData {
  assets: AssetMetric[];
  period: string;
  investment: number;
  chartElement?: HTMLElement | null;
  generatedDate: string;
}

const COLORS = {
  primary: [59, 130, 246] as [number, number, number],
  dark: [15, 23, 42] as [number, number, number],
  text: [226, 232, 240] as [number, number, number],
  muted: [148, 163, 184] as [number, number, number],
  green: [16, 185, 129] as [number, number, number],
  red: [239, 68, 68] as [number, number, number],
};

function addPageNumber(pdf: jsPDF, pageNum: number, totalPages: number) {
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  pdf.setFontSize(8);
  pdf.setTextColor(...COLORS.muted);
  pdf.text(`Page ${pageNum} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
}

function addHeader(pdf: jsPDF, title: string) {
  pdf.setFontSize(8);
  pdf.setTextColor(...COLORS.muted);
  pdf.text('Investment Analysis Report', 20, 12);
  pdf.text(title, pdf.internal.pageSize.getWidth() - 20, 12, { align: 'right' });
  pdf.setDrawColor(...COLORS.muted);
  pdf.setLineWidth(0.2);
  pdf.line(20, 14, pdf.internal.pageSize.getWidth() - 20, 14);
}

export async function generatePDF(data: ExportData): Promise<void> {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const totalPages = data.chartElement ? 3 : 2;

  // ===== PAGE 1: COVER =====
  pdf.setFillColor(...COLORS.dark);
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');

  // Title block
  pdf.setFontSize(28);
  pdf.setTextColor(...COLORS.primary);
  pdf.text('Investment Analysis', pageWidth / 2, 60, { align: 'center' });
  pdf.setFontSize(28);
  pdf.text('Report', pageWidth / 2, 72, { align: 'center' });

  // Divider
  pdf.setDrawColor(...COLORS.primary);
  pdf.setLineWidth(0.8);
  pdf.line(pageWidth / 2 - 30, 82, pageWidth / 2 + 30, 82);

  // Report details
  pdf.setFontSize(11);
  pdf.setTextColor(...COLORS.text);
  let y = 100;

  pdf.text('Selected Assets:', 40, y);
  y += 8;
  pdf.setFontSize(10);
  pdf.setTextColor(...COLORS.muted);
  const assetNames = data.assets.map(a => a.name);
  // Split into lines of max 4 assets
  for (let i = 0; i < assetNames.length; i += 4) {
    const line = assetNames.slice(i, i + 4).join(', ');
    pdf.text(line, 40, y);
    y += 6;
  }

  y += 6;
  pdf.setFontSize(11);
  pdf.setTextColor(...COLORS.text);
  pdf.text(`Analysis Period: ${data.period}`, 40, y);
  y += 10;
  pdf.text(`Initial Investment: $${data.investment.toLocaleString()}`, 40, y);
  y += 10;
  pdf.text(`Generated: ${data.generatedDate}`, 40, y);
  y += 10;
  pdf.text(`Total Assets Compared: ${data.assets.length}`, 40, y);

  // Summary stats
  y += 20;
  pdf.setDrawColor(50, 60, 80);
  pdf.setLineWidth(0.3);
  pdf.line(40, y, pageWidth - 40, y);
  y += 10;

  const bestAsset = data.assets.reduce((max, a) => a.returnPct > max.returnPct ? a : max);
  const worstAsset = data.assets.reduce((min, a) => a.returnPct < min.returnPct ? a : min);

  pdf.setFontSize(10);
  pdf.setTextColor(...COLORS.green);
  pdf.text(`Best Performer: ${bestAsset.name} (+${bestAsset.returnPct.toFixed(1)}%)`, 40, y);
  y += 8;
  pdf.setTextColor(...COLORS.red);
  pdf.text(`Worst Performer: ${worstAsset.name} (${worstAsset.returnPct.toFixed(1)}%)`, 40, y);

  // Footer branding
  pdf.setFontSize(9);
  pdf.setTextColor(...COLORS.muted);
  pdf.text('Generated by Investment Comparator — COM-480 Data Visualization', pageWidth / 2, pageHeight - 20, { align: 'center' });

  addPageNumber(pdf, 1, totalPages);

  // ===== PAGE 2: PERFORMANCE METRICS TABLE =====
  pdf.addPage();
  pdf.setFillColor(...COLORS.dark);
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');
  addHeader(pdf, 'Performance Metrics');

  y = 25;
  pdf.setFontSize(16);
  pdf.setTextColor(...COLORS.primary);
  pdf.text('Performance Summary', 20, y);
  y += 12;

  // Table header
  const colX = [20, 70, 105, 140, 170];
  pdf.setFontSize(9);
  pdf.setTextColor(...COLORS.muted);
  pdf.text('Asset', colX[0], y);
  pdf.text('Final Value', colX[1], y);
  pdf.text('Profit/Loss', colX[2], y);
  pdf.text('Return %', colX[3], y);
  pdf.text('Volatility', colX[4], y);
  y += 3;
  pdf.setDrawColor(50, 60, 80);
  pdf.setLineWidth(0.3);
  pdf.line(20, y, pageWidth - 20, y);
  y += 6;

  // Table rows
  pdf.setFontSize(9);
  data.assets.forEach((asset) => {
    if (y > pageHeight - 25) {
      pdf.addPage();
      pdf.setFillColor(...COLORS.dark);
      pdf.rect(0, 0, pageWidth, pageHeight, 'F');
      addHeader(pdf, 'Performance Metrics');
      y = 25;
    }

    pdf.setTextColor(...COLORS.text);
    pdf.text(asset.name, colX[0], y);
    pdf.text(`$${asset.finalValue.toLocaleString()}`, colX[1], y);

    const profitColor = asset.profit >= 0 ? COLORS.green : COLORS.red;
    pdf.setTextColor(...profitColor);
    pdf.text(`${asset.profit >= 0 ? '+' : ''}$${asset.profit.toLocaleString()}`, colX[2], y);
    pdf.text(`${asset.returnPct >= 0 ? '+' : ''}${asset.returnPct.toFixed(1)}%`, colX[3], y);

    pdf.setTextColor(...COLORS.muted);
    pdf.text(`${asset.volatility}%`, colX[4], y);
    y += 7;
  });

  // Category breakdown
  y += 10;
  if (y < pageHeight - 60) {
    pdf.setFontSize(12);
    pdf.setTextColor(...COLORS.primary);
    pdf.text('Category Breakdown', 20, y);
    y += 8;

    const categories = ['crypto', 'traditional', 'commodities'];
    const categoryLabels: Record<string, string> = { crypto: 'Cryptocurrencies', traditional: 'Stocks & ETFs', commodities: 'Commodities' };

    pdf.setFontSize(9);
    categories.forEach(cat => {
      const catAssets = data.assets.filter(a => a.category === cat);
      if (catAssets.length === 0) return;
      const avgReturn = catAssets.reduce((s, a) => s + a.returnPct, 0) / catAssets.length;

      pdf.setTextColor(...COLORS.text);
      pdf.text(`${categoryLabels[cat]} (${catAssets.length} assets)`, 25, y);
      const avgColor = avgReturn >= 0 ? COLORS.green : COLORS.red;
      pdf.setTextColor(...avgColor);
      pdf.text(`Avg Return: ${avgReturn >= 0 ? '+' : ''}${avgReturn.toFixed(1)}%`, 110, y);
      y += 7;
    });
  }

  addPageNumber(pdf, 2, totalPages);

  // ===== PAGE 3: CHART (if available) =====
  if (data.chartElement) {
    pdf.addPage();
    pdf.setFillColor(...COLORS.dark);
    pdf.rect(0, 0, pageWidth, pageHeight, 'F');
    addHeader(pdf, 'Performance Chart');

    y = 25;
    pdf.setFontSize(16);
    pdf.setTextColor(...COLORS.primary);
    pdf.text('Performance Evolution', 20, y);
    y += 5;

    pdf.setFontSize(9);
    pdf.setTextColor(...COLORS.muted);
    pdf.text(`All values normalized to base 100. Period: ${data.period}`, 20, y + 5);
    y += 15;

    try {
      const canvas = await html2canvas(data.chartElement, {
        backgroundColor: '#0f172a',
        scale: 2,
        logging: false,
        useCORS: true,
      });
      const imgData = canvas.toDataURL('image/png');
      const imgWidth = pageWidth - 40;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      const finalHeight = Math.min(imgHeight, pageHeight - y - 30);

      pdf.addImage(imgData, 'PNG', 20, y, imgWidth, finalHeight);
    } catch {
      pdf.setFontSize(10);
      pdf.setTextColor(...COLORS.muted);
      pdf.text('Chart could not be captured.', 20, y + 20);
    }

    addPageNumber(pdf, 3, totalPages);
  }

  // Generate filename
  const assetAbbr = data.assets.slice(0, 4).map(a => a.symbol.toUpperCase().slice(0, 3)).join('-');
  const dateSuffix = new Date().toISOString().slice(0, 10).replace(/-/g, '');
  const filename = `investment-analysis-${assetAbbr}-${data.period}-${dateSuffix}.pdf`;

  pdf.save(filename);
}
